export const CAN_GET_LOG = "CAN_GET_LOG_PERMISSION";

export const CAN_GET_RULE = "CAN_GET_RULE_PERMISSION";

export const CAN_POST_RULE = "CAN_POST_RULE_PERMISSION";

export const CAN_PUT_RULE = "CAN_PUT_RULE_PERMISSION";

export const CAN_DELETE_RULE = "CAN_DELETE_RULE_PERMISSION";

export const CAN_GET_ALARM = "CAN_GET_ALARM_PERMISSION";

export const CAN_GET_REPORT = "CAN_GET_REPORT_PERMISSION";